require:
  - solidus_dev_support/rubocop

inherit_gem:
  solidus_dev_support: .rubocop.yml

AllCops:
  Exclude:
    - spec/dummy/**/*
    - vendor/**/*

Rails/SkipsModelValidations:
  Exclude:
    - db/migrate/**/*

Gemspec/OrderedDependencies:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/MissingRespondToMissing:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/HookArgument:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Rails/CreateTableWithTimestamps:
  Enabled: false

Layout/ArgumentAlignment:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false
